const fs = require('fs')
const chalk = require('chalk')

//Api Website\\
global.APIs = {
	zenz: 'https://zenzapis.xyz',
}

//Api Key\\
global.APIKeys = {
	'https://zenzapis.xyz': 'your key',
}

global.alivemsg = `📤I am alive now😇
🤷‍♀️How can I help you?😉` //Costomize Alive Message (type your message in `` )


global.autoTyping = false //auto tying in gc (true to on, false to off)
global.autoreadpmngc = false //auto reading in gc and pm (true to on, false to off)
global.autoReadGc = false //auto reading in gc (true to on, false to off)
global.autoRecord = false //auto recording (true to on, false to off)
global.available = true //auto available (true to on, false to off)

global.doc1 = 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
global.doc2 = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
global.doc3 = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
global.doc4 = 'application/zip'
global.doc5 = 'application/pdf'
global.doc6 = 'application/vnd.android.package-archive'

//owner v card
global.vcardowner = ['+94757558130'] // owner number
global.ownername = "😎P.Indumina❯❯" // owner name
global.ytname = "" // yt chanel name
global.socialm = "GitHub: Toxic6266727" // github or insta name
global.location = "India, Mizoram, Aizawl" // location

//bot body 
global.alivepic = `https://i.ibb.co/cyyCjN7/20220803-081426.png` // alive picture \\ use "https://ibb.com" to upload photos. < 1 MB

global.dragonchat = "false"  // chat bot  "true" / "false" (200 auto replies in this)
global.callblock = "false" // call block "true" / "false" ("true"  to block callers)
global.antibad = "false" // To remove bad word senders
global.antilink = "false" // To remove group link sharing peoples
global.upsongvoice = "true" // bot can upload song as voice note (it use your data and storage bacause auto download) you can put "false" (anyone can't get songs as voice note / your data is not wasted)

global.owner = ['+380944814219']
global.ownertag = '+380944814219' //your tag number
global.botname = 'XOFIY - X BOT' //ur bot name
global.packname = "Bot Sticker" // sticker packname
global.author = "Xofiy-X" // sticker author
global.dragonemoji = '🧩' // Menu emoji
global.footer = '[ ◉ xofiy-x-md ]' //

global.button = '☰ GITHUB ☰' //Costomize A Button Name In Alive Message
global.btnurl = 'https://github.com/empty' //Change Your Button's URL

//database
global.premium = ['+94757558130'] //ur premium numbers

//other
global.sessionName = 'session.lyon'
global.antitags = false
global.prefa = ['','!','.','😂','❤️','💠'] //Command Prefix eg:(.alive ,alive 😂alive)
global.sp = '💠'
global.mess = {
    success: 'Done ✅',
    admin: 'Only Admins can use it!😉',
    botAdmin: 'Bot wants to be an Admin😥',
    owner: 'Only Owner can use this!😉',
    group: 'Feature Used Only For Groups!',
    private: 'This Features Only For Private Chat!',
    bot: 'This Feature Is Only For Bot😝',
    wait: '👉👈Pleas Wait...',
    error: 'Error!!! Maybe Api Key Is Expired🤔!',
    endLimit: 'Your Daily Limit Has Expired, The Limit Will Be Reset Every 12 Hours',
    linkm: 'Where is the link?',
    nsfw: 'The nsfw feature has not been activated, please contact the admin to activate',
    banChat: 'The bot was banned in this group, please contact the owner to unban',
    badwords: '*🚫Bad Words Not Allowed Here !*\n\n⚠️ Warning... ⚠️',
    caption: 'Generated by: ◉ *DARK-LYON-MD*'
} // END \\
    global.limitawal = {
    premium: "Infinity",
    free: 12,
    monayawal: 1000
}
   global.rpg = {
   darahawal: 100,
   besiawal: 15,
   goldawal: 10,
   emeraldawal: 5,
   umpanawal: 5,
   potionawal: 1
}
global.thum = fs.readFileSync("./Android/AllData/theme/repl.jpg") //ur thumb pic
global.log0 = fs.readFileSync("./Android/AllData/theme/repl.jpg") //ur logo pic
global.err4r = fs.readFileSync("./Android/AllData/theme/repl.jpg") //ur error pic
global.thumb = fs.readFileSync("./Android/AllData/theme/repl.jpg") //ur thumb pic

global.thumb = fs.readFileSync('./Android/AllData/theme/repl.jpg')
global.flaming = 'https://www6.flamingtext.com/net-fu/proxy_form.cgi?&imageoutput=true&script=sketch-name&doScale=true&scaleWidth=800&scaleHeight=500&fontsize=100&text='
global.fluming = 'https://www6.flamingtext.com/net-fu/proxy_form.cgi?&imageoutput=true&script=fluffy-logo&doScale=true&scaleWidth=800&scaleHeight=500&fontsize=100&text='
global.flarun = 'https://www6.flamingtext.com/net-fu/proxy_form.cgi?&imageoutput=true&script=runner-logo&doScale=true&scaleWidth=800&scaleHeight=500&fontsize=100&text='
global.flasmurf = 'https://www6.flamingtext.com/net-fu/proxy_form.cgi?&imageoutput=true&script=smurfs-logo&doScale=true&scaleWidth=800&scaleHeight=500&fontsize=100&text='

global.ntilinkytvid = []
global.ntilinkytch = []
global.ntilinkig = []
global.ntilinkfb = []
global.ntilinktg = []
global.ntilinktt = []
global.ntilinktwt = []
global.ntilinkall = []
global.nticall = []
global.ntwame = []
global.nttoxic = []
global.ntnsfw = []
global.ntvirtex = []
global.rkyt = []
global.wlcm = []
global.gcrevoke = []
global.autorep = []
global.ntilink = []





































// DO NOT CHANGE THIS. ERROR WARNING දාන්න තැනක් නැතුව මෙතන දැම්මෙ.
global.rep = { // All Replies = 145
    D1: '🫢හායි😁❤️',
    D2: '🤭හූයි✌️💞🫶',
    D3: '😉🫶හායි😂',
    D4: '🥴හූයි😊',
    D5: '😂හේයි, හව් ආ යූ🥴✌️',
    D6: '😁Hey there💝 I am WhatsApp Bot😏',
    D7: '❣️ඇයි හලෝ😌',
    D8: '🙃මොකෝ හලෝ🥲',
    D9: '😒මොකෝ?',
    D10: '🥺ඇයි අනේ?❤️🫢',
    D11: '🌝❤️',
    D12: '😜හී හී😁හූ හූ',
    D13: '😁හී හී💞',
    D14: '😊හූ...',
    D15: 'ඇයි🥲',
    D16: '😂😂✌️',
    D17: '😐ආහ්',
    D18: 'චූටී තමයි😇',
    D19: '🥺🥺ඇයි සුදූ❤️💓',
    D20: 'කොහොමවත් නෑ ඉතිං😒',
    D21: '😁මන් දන්නෑ🥲',
    D22: 'හොඳයි තමා😌',
    D23: '😂😂මරු හැබැයි',
    D24: 'මලු🙃',
    D25: '😘😇❤️',
    D26: '😘😘මෙන්න ඔයාට💕',
    D27: '😊ඇත්තමද?❤️',
    D28: '☺️👻ඔය ඇත්තමද❤️',
    D29: 'ඇයි🙄',
    D30: '🥺✌️සිදෙනවද?',
    D31: '😐💔ඕවට එන්න එපා හරිත😒',
    D32: '😏අනේ මේ😒 යනෝ යන්න💔',
    D33: 'ඔයා තමයි හොරා😒 මගෙ හිත හොරකම් කළානෙ ඉතිං😌',
    D34: '😇මොකො හූම් ගාන්නෙ😒 බකමූනා',
    D35: '​😁😁මොකෝ හලෝ හූම් හූම් ගාන්නෙ?',
    D36: '😉නෑ අනේ මුකුත් නෑ😐🫠',
    D37: '😒ආහ්',
    D38: '✌️ඔව් නං එච්චරයි😌',
    D39: '😐හේ හේ නැද්ද?🫣',
    D40: '🙄මොනවටද ආස?',
    D41: '😌මාත් ආසයි😊💞',
    D42: 'එල😌',
    D43: 'බැරි නං නිකං ඉන්න😏',
    D44: '😂😂💔',
    D45: 'සුදුයි තමයි ඇයි මොකද?🙄',
    D46: '😇තාම කෑවෙ නෑ අනේ🥺',
    K47: 'බොන්නෑ😒',
    D48: 'නිදිමත නං දිදාගන්නකො වද දෙන්නැතුව😒😌❤️',
    D49: '😇දැම්ම නිදාගන්න බෑ අනේ😜 නිදිමත නෑ😁💞',
    D50: '😉මුකුත් නෑ අනේ🫡',
    D51: 'මොකද්ද දන්නෑ🥲',
    D52: '😝මම නං මුකුත් කරන්නෑ අනේ😁 ඔයාලා දිහා බලන් ඉන්නවා😌',
    D53: '🥺පාලුයි අනේ. අපි සෙල්ලමක් කරමුද?😊✌️',
    D54: '😌😁ආදරෙයි❤️',
    D55: '😌ආදලෙයි ඉතිං❤️❤️',
    D56: '🥺🥺ඇත්තද?',
    D57: '🥺අනේ ඒ මොකද?🥴',
    D58: '😒මටත් දුකයි ඒ ගැන😕',
    D59: '🤭ඉන්න බෑ අනේ😜',
    D60: '🫡මොකද අඬන්නෙ?😒',
    D61: '😉මොකද අයියෝ😂',
    D62: '😐මුකුත් දන්නැති අහින්සක මම😕💔',
    D63: '🚲හා යමු යමු😌',
    D64: '🥴දෙන්න බෑ😒',
    D65: '🙏පස්සෙ දෙන්නං🥲',
    D66: '😁බඩගිනි නෑ❤️😒',
    D67: '😳අම්මෝ හා හා🙏',
    D68: '😂ඇයි යකෝ😉😈',
    D69: '👻ඇයි හුයි😁 කෝං ගහේ නයි😂',
    D70: '🥲දන්නැත්තං නිකං ඉන්න😜',
    D71: '😂අපි තමයි හොඳටම කරේ🥲\n🤧රෙද්ද තමයි😂',
    D72: '🙄ආ හා 😏ගහපන් බලන්න💔👎',
    D73: 'හී😂😂😂💓',
    D74: 'වන්ඩර්පුල්🥲😂',
    D75: '😂ඕං බලන්නකො ඒකෙත් හැටි නේද🥴😂',
    D76: '😌එල',
    D77: '🥲මොකෝ ඩෝ😉❣️',
    D78: 'අඩෙහ්🙃😹',
    D79: 'ඔය කිව්වට ලොකු නෑ හොඳේ😏',
    D80: '😹මම නං පොඩී තමයි ඉතිං😌',
    D81: '🥴ටිකයි ද?😂',
    D82: '🥴ඒකි එහෙම නෑ බන්😅',
    D83: '🥲ඌ මොකද්ද කරේ?',
    D84: '😂එහෙම කියන්න එපා එයාලා පව්නෙ😐🤭',
    D85: 'හුම්ම්😌 පව් ඉතිං😂',
    D86: 'හා😒 කියනකං තමයි හිටියෙ🙏❣️',
    D87: 'මන් දන්නෑ🥲',
    D88: '  👀  ',
    D89: '🥺ගිහින් බේත් ගන්න',
    D90: '🥺ගොඩක් අමාරුද?☝️',
    D91: 'DSI පාරක් කන්න ආසද?😂',
    D92: 'කලිසම ගලවනෝකො ඉතිං😒',
    D93: 'අත ලෙප්ට්🥲',
    D94: '🫢🫢හරි නරකයි😒',
    D95: '😌මම නං කොහොමත් අහින්සකයි රටක් වටී😁❤️',
    D96: 'අතේ...🥲🥲🥲🥲🥲🥲',
    D97: '😐දාන්න බෑ😒',
    D98: '📱🔌පෝන එක චාජ් එකට ගහලා ඔය ළමයා ගිහින් වැඩක් කරගන්න😉',
    D99: '🫢🤭ඇයි? අසහනේ ද?🤨😏💔',
    D100: '💔පෙම් සිත රිදුනා සත්තලනේ🥺🤧',
    D101: '😹😹☝️',
    D102: 'බල්ලා පූසා මීයා හාවා නරියා අලියා😒',
    D103: '🥲උරුලා ගති තමා',
    D104: '😐කියන්න බෑ😒 ඇයි මොකෝ?🙄',
    D105: '😐අපි පැනල යමුද?🤭🫢',
    D106: '☝️ගියා නං ආයි එන්නෙපා😒',
    D107: '😅✌️😝',
    D108: '😂😂විහිලු නං කමක් නෑ😌',
    D109: 'මං තරහයි😒 ඇයි මොකෝ?👎',
    D110: 'ඇයි පකෝ🥲',
    D111: 'ලබ්බ😒',
    D112: 'මොන හුම්තක්ද යකෝ?🙄',
    D113: '😒පලෑන්න පොන්නය💔',
    D114: '🥲💔🙏',
    D115: '🥲🥲💔☝️',
    D116: '😏😑එන්නෙපා ගෑනි ගාගෙන🤨💔💔💔',
    D117: 'දැන්ම බෑ ළමයෝ🤭🤭 පස්සෙ දෙන්නං😝😒',
    D118: 'මොන පකක්ද?😒',
    D119: '😒👎',
    D120: 'එහෙම කියන්නෙපා පව්නෙ😒',
    D121: '🫢🙄',
    D122: 'අනේ තෝ හුකාගනිං🙂💔',
    D123: '😐උක්කමු😒😂😂',
    D124: 'ඇයි🙄 පුකද බලන්නෙ?',
    D125: 'උබේ දෙක ද?😂',
    D126: 'උබේ ද?😂',
    D127: '🥲මං ඇවිත් කටට ගන්නද?😒😝',
    D128: '😂😂හමෝ',
    D129: '😏ඕන්නැත්තං නිකං ඉන්න',
    D130: '🤭නිකං ඉන්න එපා ඇඳුමක් ඇඳගන්න😂❤️',
    D131: '😂😂🙏',
    D132: '😂🤭',
    D133: '😁',
    D134: '😏☝️',
    D135: 'අඬන්න එපා ඉතිං😒😝',
    D136: '🥴පිත්තු',
    D137: '🙂',
    D138: '😌😌',
    D139: '🥲🥲💔',
    D140: '😍🥰😘💞💕💓💗💖❣️❤️',
    D141: '😐🙄',
    D142: '🥺දුක් වෙන්න එපා ඉතිං❤️',
    D143: '🥺🥺😐',
    D144: '❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️',
    D145: '🫡🫠🤝',
    D146: '🎤දහසක් මල්🌸 විකසිත වන😊 මේ හිමිදිරි උදෑසනේ🌄 පතන්නම් ඔබ සැමට🙏 සුභම සුභ උදෑසනක් කියා...😃',
    D147: 'ලබන්නාවූ රාත්‍රිය හීනෙන් හොල්මන් පෙනෙන, මහ රෑ දාඩියෙන් තෙමී ඇහැරෙන, පෙරේතයන් ඇද යටට එන, කුම්භාණ්ඩයින් ජනෙල් වලින් එබී බලන, භයානක රාත්‍රියක් වේවා😂👻👻❤️'
    }






let file = require.resolve(__filename)
fs.watchFile(file, () => {
	fs.unwatchFile(file)
	console.log(chalk.redBright(`Update'${__filename}'`))
	delete require.cache[file]
	require(file)
})
